# Generated by Django 3.2.5 on 2021-08-04 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('game_type', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('first_prize', models.IntegerField()),
                ('second_prize', models.IntegerField()),
                ('third_prize', models.IntegerField()),
                ('last_reg_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tournament_image', models.ImageField(upload_to='tournament_image')),
                ('required_rank', models.IntegerField(max_length=3)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
