# Generated by Django 3.2.5 on 2021-08-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='slots',
            field=models.IntegerField(default=25, max_length=2),
        ),
    ]
