# Generated by Django 3.2.5 on 2021-08-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournamentmodel_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='team_type',
            field=models.CharField(default='4v4', max_length=3),
        ),
    ]
