# Generated by Django 3.2.5 on 2021-08-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournamentmodel_team_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='description',
            field=models.CharField(default='This is match description', max_length=500),
        ),
    ]
