# Generated by Django 3.2.5 on 2021-08-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_auto_20210805_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsmodel',
            name='bkash_payment_number',
            field=models.IntegerField(default=10000000),
        ),
        migrations.AddField(
            model_name='teamsmodel',
            name='bkash_trxid',
            field=models.IntegerField(default=10000000),
        ),
    ]
