# Generated by Django 3.2.5 on 2021-08-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_auto_20210806_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsmodel',
            name='bkash_payment_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamsmodel',
            name='bkash_trxid',
            field=models.IntegerField(),
        ),
    ]
