# Generated by Django 3.2.5 on 2021-08-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_auto_20210806_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsmodel',
            name='name',
            field=models.CharField(default='My Team', max_length=150),
        ),
    ]
