# Generated by Django 3.2.5 on 2021-08-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_teamsmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamsmodel',
            name='player4',
        ),
    ]
