# Generated by Django 3.2.5 on 2021-08-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_auto_20210807_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsmodel',
            name='payment_ammount',
            field=models.FloatField(),
        ),
    ]
