# Generated by Django 3.2.5 on 2021-08-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_alter_teamsmodel_payment_ammount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentmodel',
            old_name='last_updated',
            new_name='start_date',
        ),
    ]
