# Generated by Django 3.2.5 on 2021-08-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_rename_last_updated_tournamentmodel_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='start_time',
            field=models.TimeField(default='10:40 AM'),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='last_reg_date',
            field=models.DateField(default='00/00/0000'),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='start_date',
            field=models.DateField(default='00/00/0000'),
        ),
    ]
