# Generated by Django 3.2.5 on 2021-08-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_auto_20210809_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmodel',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='last_reg_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
