# Generated by Django 3.2.5 on 2021-08-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_alter_tournamentmodel_last_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='start_date',
            field=models.DateField(),
        ),
    ]
