# Generated by Django 3.2.5 on 2021-08-09 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_alter_tournamentmodel_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 30)),
        ),
    ]
