# Generated by Django 3.2.5 on 2021-08-18 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0018_auto_20210818_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamsmodel',
            name='leader',
        ),
        migrations.AddField(
            model_name='teamsmodel',
            name='leader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
