# Generated by Django 3.2.5 on 2021-08-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_auto_20210819_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='total_prize',
            field=models.IntegerField(default=0),
        ),
    ]
