# Generated by Django 3.2.5 on 2021-08-25 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_tournamentmodel_total_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='total_prize',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='MatchsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default=None, max_length=100)),
                ('room_password', models.CharField(default=None, max_length=100)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournamentmodel')),
            ],
        ),
    ]
