# Generated by Django 3.2.5 on 2021-08-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_auto_20210825_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchsmodel',
            name='room_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matchsmodel',
            name='room_password',
            field=models.CharField(max_length=100),
        ),
    ]
