# Generated by Django 3.2.5 on 2021-08-28 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_auto_20210825_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_image', models.ImageField(upload_to='winners')),
                ('first_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner1', to='tournaments.teamsmodel')),
                ('second_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner2', to='tournaments.teamsmodel')),
                ('third_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner3', to='tournaments.teamsmodel')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champions', to='tournaments.tournamentmodel')),
            ],
        ),
    ]
