# Generated by Django 3.2.5 on 2021-08-28 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0025_winnermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnermodel',
            name='tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='champions', to='tournaments.tournamentmodel'),
        ),
    ]
